version: '2.4'
services:
    watchtower:
        container_name: watchtower
        restart: unless-stopped
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/etc/localtime:/etc/localtime:ro'
        command:
            --cleanup
        image: containrrr/watchtower